### PR TITLE
sstar: SoC temperature over sysfs on original firmware

### PR DESCRIPTION
**Pull request by ch999dev**
checked on MY-E10 (anjvision/PTZ)

### CODE REVIEW

**Comment by ch999dev** [comment]
2nd patch adds some extended board information like this (MY-E10 board again, but should work with almost any sstar-sdk based builds)
```
---
board:
  model: INFINITY6B0 SSC009A-S01A QFN88
  Chip_ID: 0xF2
  Chip_Version: 1
  SoC_Family:I6B0
  SoC_Id:242
  SoC_Revision:2
```

**Comment by ZigFisher** [comment]
Nice work, man !  Respect !

And we can then add that the human name of the processor is displayed on the command --chip ?
In this case, we need ssc335

**Comment by ch999dev** [comment]
I've not looked whether there is a SoC {Family,Id} == 'commercial chip name' correspondence table anywhere. 
BTW MY-E10 is SSC335+GC2053. At least I can see drv_ms_cus_gc2053_MIPI in loaded driver list

**Comment by ZigFisher** [comment]
Yes. We'll need to discuss this detail with Dimitri..

**Comment by ZigFisher** [comment]
> 2nd patch adds some extended board information like this (MY-E10 board again, but should work with almost any sstar-sdk based builds)
> 
> ```
> ---
> board:
>   model: INFINITY6B0 SSC009A-S01A QFN88
>   Chip_ID: 0xF2
>   Chip_Version: 1
>   SoC_Family:I6B0
>   SoC_Id:242
>   SoC_Revision:2
> ```

The temperature works well. 
But the chip data is not visible in the OpenIPC firmware.

 Did you get this data only on the manufacturer's firmware?

**Comment by ch999dev** [comment]
Yes. I checked it on the stock firmware of Anji. It seems many (if not all) current sstar builds use the same set of libmi _ * .so libraries and drivers from the SDK. These drivers have provided some information on /sys/class/mstar/msys/,  etc on all sstar platforms.
Some builds used static * .a libraries built directly into applications.
Unfortunately, these libraries do not exist for musl (only uClibC / gLibC if I remember correctly).

**Comment by ZigFisher** [comment]
Thank you for the valuable information, we will understand..
Please open the issue on this here

**Comment by widgetii** [comment]
BTW, (sorry for skipped it previously from my side): consider using `kebab-case` for YAML keys like:
Chip_Version -> chip-version and so on because we used it before in other attributes like `u-mdio-phyaddr`, `phy-id`, `god-app` just for the sake of consistency.

**Comment by ch999dev** [comment]
done. #20

**Pull request merged**
