### PR TITLE
Makes firmware uploads to the cloud explicit.

### PR DESCRIPTION
**Pull request by gckzl**
* stops making autodumps when run without arguments.
 * adds a separate `upload` command, to make it clear the data is leaving the local network
 * moves the backup / upload work to the main process: no more background processes
 * refactors the MTD code to work with cJSON objects instead of printing to stdout

One side-effect of this change is that STDOUT isn't flushed anymore before trying to detect the sensors: all output happens after all the data has been collected.

Another change is that the output skips the initial "---" marker, making it a "bare document" in YAML terms.  Since we're only producing a single document, this shouldn't make any difference.

### CODE REVIEW

**Comment by viktorxda** [comment]
Initial test seems to work as intended, however the layout for the rom output needs to be adjusted:
```
rom:
  - type: nor
    block: 64K
    partitions:
      - name: boot
        size: 0x40000
        sha1: 1c85bdf3
      - name: env
        size: 0x10000
        sha1: ad0c9c90
        contains:
          - name: uboot-env
            offset: 0x0
      - name: kernel
        size: 0x300000
        sha1: 1913cb20
      - name: rootfs
        size: 0xa00000
        sha1: 1761a48d
      - name: rootfs_data
        size: 0x2b0000
        path: /overlay,jffs2,rw
    size: 16M
```

```
rom:
- type: nor
  block: 64K
  partitions:
-     name: boot
    size: 0x40000
    sha1: 1c85bdf3
-     name: env
    size: 0x10000
    sha1: ad0c9c90
    contains: "          - name: uboot-env\n            offset: 0x0\n"
-     name: kernel
    size: 0x300000
    sha1: 1913cb20
-     name: rootfs
    size: 0xa00000
    sha1: 1761a48d
-     name: rootfs_data
    size: 0x2b0000
    path: /overlay,jffs2,rw
  size: 16M
```

**Comment by viktorxda** [comment]
Small layout difference:
```
sensors:
- vendor: GalaxyCore
  model: GC4653
  control:
    bus: 0
    type: i2c
    addr: 0x52
```
```
sensors:
  - vendor: GalaxyCore
    model: GC4653
    control:
      bus: 0
      type: i2c
      addr: 0x52
```

**Comment by widgetii** [comment]
Thank you, looks very good, I'll test everything on my devices this weekend

**Comment by widgetii** [comment]
Not yet, may be this weekend. If colleagues can make tests on their real devices, let's merge it early

**Comment by viktorxda** [comment]
Here is a output test from a ingenic device:
<details>
<summary>ipctool-mipsel</summary>

```
---
chip:
  vendor: Ingenic
  model: T21N
board:
  vendor: OpenIPC
  version: 2.3.07.23
ethernet:
  mac: "xx:xx:xx:xx:xx:xx"
rom:
- type: nor
  block: 32K
  partitions:
    - name: boot
      size: 0x40000
      sha1: 35bc366c
    - name: env
      size: 0x10000
      sha1: b38f0062
      contains:
        - name: uboot-env
          offset: 0x0
    - name: kernel
      size: 0x300000
      sha1: 13ebde61
    - name: rootfs
      size: 0xa00000
      path: /,squashfs
      sha1: 5af257af
    - name: rootfs_data
      size: 0x2b0000
      path: /overlay,jffs2,rw
  size: 16M
ram:
  total: 64M
  media: 24M
firmware:
  kernel: "3.10.14__isvp_turkey_1.0__ (PREEMPT Sun Jul 23 18:06:21 UTC 2023)"
  toolchain: buildroot-gcc-12.2.0
sensors:
- vendor: Silicon Optronics
  model: JXF37
  control:
    bus: 0
    type: i2c
    addr: 0x80
```
</details>

One thing to note is the slight delay between the execution and the output, as previously mentioned.
Maybe you could add a message that indicates that the process is collecting the information.

**Comment by widgetii** [comment]
> Maybe you could add a message that indicates that the process is collecting the information.

In this case it will be not valid YAML anymore

**Comment by viktorxda** [comment]
I see. Otherwise I didn't notice any problems, here is a test sample from another device:

<details>
<summary>openipc-hi3516ev300</summary>

```
root@openipc-hi3516ev300:~# /tmp/ipctool
---
chip:
  vendor: HiSilicon
  model: 3516EV300
  id: 000000000000000000000000000000000000000000000000
board:
  vendor: OpenIPC
  version: 2.3.07.23
  possible-IR-cut-GPIO: 7
ethernet:
  mac: "xx:xx:xx:xx:xx:xx"
  u-mdio-phyaddr: 1
  phy-id: 0x20669903
  d-mdio-phyaddr: 0
rom:
- type: nor
  block: 64K
  partitions:
    - name: boot
      size: 0x40000
      sha1: c35c806b
    - name: env
      size: 0x10000
      sha1: 017ca834
      contains:
        - name: uboot-env
          offset: 0x0
    - name: kernel
      size: 0x300000
      sha1: fbe4ae1b
    - name: rootfs
      size: 0xa00000
      sha1: ea1e905e
    - name: rootfs_data
      size: 0x2b0000
      path: /overlay,jffs2,rw
  size: 16M
  addr-mode: 3-byte
ram:
  total: 128M
  media: 96M
firmware:
  kernel: "4.9.37 (Sun Jul 23 17:53:37 UTC 2023)"
  toolchain: buildroot-gcc-12.2.0
  sdk: "Hi3516EV200_MPP_V1.0.1.2 B030 Release (Oct 18 2019, 18:21:00)"
  main-app: /usr/bin/majestic
sensors:
- vendor: Sony
  model: IMX335
  control:
    bus: 0
    type: i2c
    addr: 0x34
  data:
    type: MIPI
    input-data-type: DATA_TYPE_RAW_12BIT
    lane-id:
      - 0
      - 1
      - 2
      - 3
    image: 2592x1944
  clock: 37.125MHz
```
</details>

**Comment by widgetii** [comment]
Ok, let's merge then

@gckzl thank for your efforts

**Comment by dimerr** [comment]
@gckzl 

This PR breaks output of https://github.com/OpenIPC/ipctool/blob/master/src/boards/xm.c#L47
Before:
```

    chip:
      name: "XM_XM25QH128C"
      id: 0x204018
```
After:
`      chip: "      name: \"XM_XM25QH128C\"\n      id: 0x204018\n"`

**Pull request merged**
